library(shiny)

# Define UI for app that draws a histogram ----
ui <- fluidPage(
  
  titlePanel("Which Tiff & Yves hybrid unlocks your bucks!"),
  
  mainPanel(
      plotOutput(outputId = "origPlot"),
      h6("Unlock your bucks by reconstructing our Tiff & Yves hybrid.
      Hybrids are constructed by recombining the first 30 eigenvectors of an SVD on the original Tiff and Yves pics."),  

      sliderInput(inputId = "seed",
                  label="",
                 min = 0,
                 max = 999,
                 value = 0, step=1),
      actionButton("minus", "-"),
      actionButton("plus", "+"),
      plotOutput(outputId = "searchPlot"),
      h6("Copyright on original images by Yves Gabriëls. The rds files and the images generated by this tool are not allowed to be used without permission of the copyright holder of the original images.")
    )
#  )
)