library(shiny)

# Define UI for app that draws a histogram ----
ui <- fluidPage(
  
  titlePanel("Which Tiff & Yves hybrid unlocks your bucks?"),
  
  fluidRow(
    splitLayout(
      plotOutput("tiffOrig"),
      plotOutput("plotToFind"),
      plotOutput("yvesOrig")
      )),
  mainPanel(widht=12,
    h4("Unlock your bucks by reconstructing our Tiff & Yves hybrid.
      Hybrids can be constructed by scrambling the first 30 eigenvectors of an SVD of original Tiff & Yves pics using the slider."),  
    br(),
    
    sliderInput(inputId = "seed",
                label="",
                min = 0,
                max = 999,
                value = 0, step=1),

    actionButton("minus", "-"),
    actionButton("plus", "+"),
    br()),
    fluidRow(
    splitLayout(
      plotOutput("approxTiff"),
      plotOutput("approxSam"),
      plotOutput("approxYves")    
      )),
    mainPanel(width=12,
    h4("Hybrid showdown"),
    span(textOutput("printCode"), 
         style ="font-size:15px; font-family:arial"),
    br()),
    fluidRow(
    splitLayout(
      plotOutput("plotToFindComp"),
      plotOutput("approxSamComp")    
      )),
    mainPanel(width=12,
    h6("Copyright on original images by Yves Gabriëls. The rds files and the images generated by this tool are not allowed to be used without permission of the copyright holder of the original images.")
    ))
