library(shiny)

# Define UI for app that draws a histogram ----
ui <- fluidPage(
  
  # App title ----
  titlePanel("Which Tiff & Yves hybrid unlocks your bucks!"),
  
  # Sidebar layout with input and output definitions ----
  sidebarLayout(
    
    # Sidebar panel for inputs ----
    sidebarPanel(
      
      # Input: Slider for the number of bins ----
      #sliderInput(inputId = "seed",
      #            label = "Change the seed to generate a new plot:",
      #            min = 1,
      #            max = 999,
      #            value = 397),
      sliderInput(inputId = "seedH",
                  label = "Change the seed to generate a new plot:",
                  min = 0,
                  max = 9,
                  value = 5, step = 1),
      sliderInput(inputId = "seedT",
                  label = "",
                  min = 0,
                  max = 9,
                  value = 5, step = 1),
      sliderInput(inputId = "seedE",
                  label = "",
                  min = 0,
                  max = 9,
                  value = 5, step = 1)
      
    ),
    
    # Main panel for displaying outputs ----
    mainPanel(
      
      # Output: Histogram ----
      h6("From the Tiff & Yves pics on the mariage invitation we constructed a Tiff & Yves hybrid using the singular value decomposition. 
         We only used the first 30 components. We randomly took 15 components of Tiff and the other 15 from Yves. 
         Unlock your bucks by reconstructing my Tiff & Yves hybrid (middle pic in the bottom row). 
         Tip: Experiment with the slider to randomly select 15 components from Tiff and Yves (left and right pics) to be merged in your new Tiff and Yves hybrid in the middle!"),
      plotOutput(outputId = "searchPlot"),
      h6("The original plots and the Tiff & Yves hybrid you need to reconstruct to unlock your bucks"),
      plotOutput(outputId = "origPlot"),
      h6("Copyright on original images by Yves Gabriëls. The rds files and the images generated by this tool are not allowed to be used without permission of the copyright holder of the original images.")
    )
  )
)